function [ visualAttnOutData ] = displayClassificationStats( visualAttnInData )
%DISPLAYCLASSIFICATIONSTATS Displays classifaction statistics generated by
%this method on scallop and non-scallop objects primarily based on the
%number of random variables matched by scallop distribution

%% Initialization
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

visualAttnOutData = visualAttnInData;

%% Classification Histograms
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
scallopDistrMatchCounts = [];
nonScallopDistrMatchCounts = [];

for imageI=1:length(visualAttnOutData.statData.category)
    for fixI=1:length(visualAttnOutData.statData.category(imageI).fixations)
        for objI=1:length(visualAttnOutData.statData.category(imageI).fixations{fixI})
            switch visualAttnOutData.statData.category(imageI).fixations{fixI}(objI)
                case 1
                scallopDistrMatchCounts = ...
                    [scallopDistrMatchCounts visualAttnOutData.distributionData.dataPointCheck{imageI}{fixI}{objI}.scallopMatchPoints];
                case 0
                nonScallopDistrMatchCounts = ...
                    [nonScallopDistrMatchCounts visualAttnOutData.distributionData.dataPointCheck{imageI}{fixI}{objI}.scallopMatchPoints];
            end
        end
    end
end
                    
figure;hist( scallopDistrMatchCounts(:) );
figure;hist( nonScallopDistrMatchCounts(:) );

end

